use std::io::{self, Write};

use crate::falcon_api::FalconClient;
use crate::sensor_store::SensorLister;

pub struct Answers {
    pub client_id: String,
    pub client_secret: String,
    pub cloud: String,
    pub cid: String,
    pub port: u16,
    pub bind: String,
    pub addr: Option<String>,
    pub public_url: Option<String>,
    pub token: Option<String>,
    pub tags: Option<String>,
    pub cache_dir: String,
    pub metadata_ttl_minutes: u64,
    pub cache_max_bytes: u64,
}

pub struct InstallPlan {
    pub config_toml: String,
    pub port: u16,
    pub cache_dir: String,
    pub enable_auto_update: bool,
    pub base_url_hint: String,
}

/// TOML-екранування рядка: лише лапки й бекслеші, решта — як є.
fn toml_string(value: &str) -> String {
    let escaped = value.replace('\\', "\\\\").replace('"', "\\\"");
    format!("\"{escaped}\"")
}

pub fn render_config(a: &Answers) -> String {
    let mut out = String::new();
    out.push_str("# Generated by 'pike service-install'\n\n[server]\n");
    out.push_str(&format!("bind = {}\n", toml_string(&a.bind)));
    out.push_str(&format!("port = {}\n", a.port));
    if let Some(addr) = &a.addr {
        out.push_str(&format!("addr = {}\n", toml_string(addr)));
    }
    if let Some(url) = &a.public_url {
        out.push_str(&format!("public_url = {}\n", toml_string(url)));
    }
    if let Some(token) = &a.token {
        out.push_str(&format!("token = {}\n", toml_string(token)));
    }
    out.push_str("timeout_minutes = 0\nmax_downloads = 0\n");

    out.push_str("\n[falcon]\n");
    out.push_str(&format!("client_id = {}\n", toml_string(&a.client_id)));
    out.push_str(&format!(
        "client_secret = {}\n",
        toml_string(&a.client_secret)
    ));
    out.push_str(&format!("cloud = {}\n", toml_string(&a.cloud)));
    out.push_str(&format!("cid = {}\n", toml_string(&a.cid)));

    out.push_str("\n[sensors]\n");
    out.push_str(&format!("cache_dir = {}\n", toml_string(&a.cache_dir)));
    out.push_str(&format!(
        "metadata_ttl_minutes = {}\n",
        a.metadata_ttl_minutes
    ));
    out.push_str(&format!("cache_max_bytes = {}\n", a.cache_max_bytes));
    if let Some(tags) = &a.tags {
        out.push_str(&format!("tags = {}\n", toml_string(tags)));
    }
    out.push_str("default_tag = true\n");
    out
}

fn prompt(label: &str, default: Option<&str>) -> String {
    loop {
        match default {
            Some(d) => print!("{label} [{d}]: "),
            None => print!("{label}: "),
        }
        io::stdout().flush().ok();
        let mut line = String::new();
        if io::stdin().read_line(&mut line).is_err() {
            continue;
        }
        let line = line.trim().to_string();
        if !line.is_empty() {
            return line;
        }
        if let Some(d) = default {
            return d.to_string();
        }
        eprintln!("  (this one is required)");
    }
}

fn prompt_optional(label: &str) -> Option<String> {
    let v = prompt_allow_empty(label);
    if v.is_empty() { None } else { Some(v) }
}

fn prompt_allow_empty(label: &str) -> String {
    print!("{label} (leave empty to skip): ");
    io::stdout().flush().ok();
    let mut line = String::new();
    io::stdin().read_line(&mut line).ok();
    line.trim().to_string()
}

/// Питає, доки відповідь не пройде перевірку. Візард обіцяє, що все
/// перевірене ще до першого запису на диск — інакше про помилку в токені
/// чи bind дізнаєшся аж від `systemctl`, коли сервіс уже встановлено.
fn prompt_valid<T>(
    label: &str,
    default: Option<&str>,
    validate: impl Fn(&str) -> Result<T, String>,
) -> T {
    loop {
        let raw = prompt(label, default);
        match validate(&raw) {
            Ok(v) => return v,
            Err(e) => eprintln!("  ({e})"),
        }
    }
}

fn validate_bind(value: &str, port: u16) -> Result<String, String> {
    // Перевіряємо рівно те, що робитиме сервер на старті
    format!("{value}:{port}")
        .parse::<std::net::SocketAddr>()
        .map(|_| value.to_string())
        .map_err(|_| format!("'{value}' is not an IP address pike can bind to"))
}

fn validate_cache_dir(value: &str) -> Result<String, String> {
    if !value.starts_with('/') {
        return Err("must be an absolute path".into());
    }
    // Пробіл розділив би значення в ReadWritePaths= і зламав юніт
    if value.split_whitespace().count() != 1 {
        return Err("must not contain whitespace".into());
    }
    Ok(value.to_string())
}

fn prompt_bool(label: &str, default: bool) -> bool {
    let hint = if default { "Y/n" } else { "y/N" };
    loop {
        print!("{label} [{hint}]: ");
        io::stdout().flush().ok();
        let mut line = String::new();
        io::stdin().read_line(&mut line).ok();
        match line.trim().to_lowercase().as_str() {
            "" => return default,
            "y" | "yes" => return true,
            "n" | "no" => return false,
            _ => eprintln!("  (answer y or n)"),
        }
    }
}

/// Збирає відповіді й перевіряє їх проти API. Нічого не пише на диск.
pub fn run() -> Result<InstallPlan, String> {
    eprintln!("pike service installer");
    eprintln!("──────────────────────\n");

    let cloud = prompt(
        "CrowdStrike cloud (us-1/us-2/eu-1/us-gov-1/us-gov-2)",
        Some("eu-1"),
    );
    let client_id = prompt("API Client ID", None);
    let client_secret =
        rpassword::prompt_password("API Client Secret: ").map_err(|e| e.to_string())?;

    eprintln!("\nValidating credentials against the API...");
    let rt = tokio::runtime::Runtime::new().map_err(|e| e.to_string())?;
    let api_cid = rt.block_on(async {
        let client = FalconClient::new(&client_id, &client_secret, Some(&cloud))
            .await
            .map_err(|e| format!("authentication failed: {e}"))?;
        let cid = client
            .get_ccid()
            .await
            .map_err(|e| format!("cannot fetch CCID: {e}"))?;
        // Перевіряємо саме той скоуп, без якого сервер марний
        client.list("linux").await.map_err(|e| {
            format!("sensor listing failed — is the 'Sensor Download: Read' scope granted? ({e})")
        })?;
        Ok::<_, String>(cid)
    })?;
    eprintln!("  OK — CID {api_cid}\n");

    let cid = prompt("Customer ID", Some(&api_cid));

    let port: u16 = loop {
        let raw = prompt("HTTP port", Some("8080"));
        match raw.parse() {
            Ok(p) => break p,
            Err(_) => eprintln!("  (not a valid port)"),
        }
    };
    let bind = prompt_valid("Bind address", Some("0.0.0.0"), |v| validate_bind(v, port));

    eprintln!("\nDetected addresses:");
    let addrs = crate::util::detect_available_addrs();
    for (i, (label, _)) in addrs.iter().enumerate() {
        eprintln!("  {i}) {label}");
    }
    let addr = loop {
        let raw = prompt_allow_empty("Advertised address — index or literal");
        if raw.is_empty() {
            break None;
        }
        // Число поза списком — це майже напевно помилка при виборі пункту,
        // а не адреса; записати його як літерал означало б віддати хостам
        // ванлайнер виду http://4:8080/<token>
        match raw.parse::<usize>() {
            Ok(i) if i < addrs.len() => break Some(addrs[i].1.clone()),
            Ok(_) => eprintln!("  (no such index; pick 0-{})", addrs.len() - 1),
            Err(_) => break Some(raw),
        }
    };

    let public_url =
        prompt_optional("Public URL behind a reverse proxy, e.g. https://pike.lab.local");

    let generated = crate::util::generate_token();
    eprintln!("\nGenerated token: {generated}");
    let token = Some(prompt_valid("Token", Some(&generated), |v| {
        crate::config::validate_token(v)
            .map(|()| v.to_string())
            .map_err(|e| e.to_string())
    }));

    let tags = prompt_optional("Grouping tags, comma-separated");
    let cache_dir = prompt_valid(
        "Cache directory",
        Some(crate::config::DEFAULT_SERVICE_CACHE_DIR),
        |v| validate_cache_dir(v),
    );
    let enable_auto_update = prompt_bool(
        "\nEnable the weekly auto-update timer? (pike is 0.x and may introduce breaking changes)",
        false,
    );

    let answers = Answers {
        client_id,
        client_secret,
        cloud,
        cid,
        port,
        bind,
        addr: addr.clone(),
        public_url: public_url.clone(),
        token: token.clone(),
        tags,
        cache_dir: cache_dir.clone(),
        metadata_ttl_minutes: crate::config::DEFAULT_METADATA_TTL_MINUTES,
        cache_max_bytes: crate::config::DEFAULT_CACHE_MAX_BYTES,
    };

    let host = public_url.unwrap_or_else(|| {
        format!(
            "http://{}:{}",
            addr.unwrap_or_else(|| "127.0.0.1".into()),
            port
        )
    });
    let base_url_hint = match &token {
        Some(t) => format!("{host}/{t}"),
        None => host,
    };

    Ok(InstallPlan {
        config_toml: render_config(&answers),
        port,
        cache_dir,
        enable_auto_update,
        base_url_hint,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn answers() -> Answers {
        Answers {
            client_id: "abc".into(),
            client_secret: "s3cr3t".into(),
            cloud: "eu-1".into(),
            cid: "AABBCC-01".into(),
            port: 8080,
            bind: "0.0.0.0".into(),
            addr: Some("10.20.0.5".into()),
            public_url: None,
            token: Some("labtoken01".into()),
            tags: Some("lab/crowdstrike".into()),
            cache_dir: "/var/cache/pike".into(),
            metadata_ttl_minutes: 60,
            cache_max_bytes: 21_474_836_480,
        }
    }

    #[test]
    fn config_roundtrips_through_the_parser() {
        let toml_text = render_config(&answers());
        let parsed: crate::config::FileConfig =
            toml::from_str(&toml_text).expect("generated config must parse");
        assert_eq!(parsed.server.port, Some(8080));
        assert_eq!(parsed.falcon.cloud.as_deref(), Some("eu-1"));
        assert_eq!(
            parsed.sensors.cache_dir.as_deref(),
            Some(std::path::Path::new("/var/cache/pike"))
        );
    }

    #[test]
    fn config_includes_token_and_tags() {
        let toml_text = render_config(&answers());
        assert!(toml_text.contains(r#"token = "labtoken01""#));
        assert!(toml_text.contains(r#"tags = "lab/crowdstrike""#));
    }

    #[test]
    fn optional_fields_are_omitted_when_absent() {
        let mut a = answers();
        a.public_url = None;
        a.addr = None;
        a.tags = None;
        let toml_text = render_config(&a);
        assert!(!toml_text.contains("public_url"));
        assert!(!toml_text.contains("addr ="));
        assert!(!toml_text.contains("tags ="));
        // і згенероване все одно має розбиратись
        toml::from_str::<crate::config::FileConfig>(&toml_text).unwrap();
    }

    // --- валідація ---

    #[test]
    fn bind_accepts_addresses_the_server_can_parse() {
        assert!(validate_bind("0.0.0.0", 8080).is_ok());
        assert!(validate_bind("127.0.0.1", 8080).is_ok());
    }

    #[test]
    fn bind_rejects_hostnames() {
        // `localhost` пройшов би візард, але впав би на старті сервера
        assert!(validate_bind("localhost", 8080).is_err());
        assert!(validate_bind("", 8080).is_err());
    }

    #[test]
    fn cache_dir_must_be_absolute_and_space_free() {
        assert!(validate_cache_dir("/var/cache/pike").is_ok());
        assert!(validate_cache_dir("var/cache/pike").is_err());
        // Пробіл розділив би значення в ReadWritePaths=
        assert!(validate_cache_dir("/var/cache/my pike").is_err());
    }

    #[test]
    fn wizard_rejects_tokens_the_config_would_refuse() {
        assert!(crate::config::validate_token("lab/token").is_err());
        assert!(crate::config::validate_token("labtoken01").is_ok());
    }

    #[test]
    fn secrets_are_quoted_safely() {
        let mut a = answers();
        a.client_secret = r#"has"quote\and\backslash"#.into();
        let toml_text = render_config(&a);
        let parsed: crate::config::FileConfig = toml::from_str(&toml_text).unwrap();
        assert_eq!(
            parsed.falcon.client_secret.as_deref(),
            Some(r#"has"quote\and\backslash"#)
        );
    }
}
