[package]
name = "pike"
version = "0.3.0"
edition = "2024"
description = "CrowdStrike Falcon sensor deployment tool"
authors = ["Stanislav <ih3xcode@protonmail.com>"]
license = "MIT"
repository = "https://github.com/ih3xcode/pike"

[dependencies]
arboard = "3.6.1"
axum = "0.8.8"
bytes = "1"
chrono = "0.4.43"
clap = { version = "4.5.57", features = ["derive", "env"] }
eframe = { version = "0.33.3", default-features = false, features = ["default_fonts", "wgpu", "wayland", "x11"] }
hex = "0.4.3"
local-ip-address = "0.6.10"
rand = "0.9.2"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rfd = "0.17.2"
sha2 = "0.10.9"
tokio = { version = "1.49.0", features = ["full"] }
thiserror = "2.0.18"
wgpu = "27"
semver = "1"
self-replace = "1.5.0"
tempfile = "3.25.0"
toml = "0.9"

[profile.release]
lto = true
strip = true
opt-level = "z"
codegen-units = 1
panic = "abort"
