use super::Answers;

/// TOML string escaping: quotes and backslashes only, the rest verbatim.
fn toml_string(value: &str) -> String {
    let escaped = value.replace('\\', "\\\\").replace('"', "\\\"");
    format!("\"{escaped}\"")
}

pub(super) fn render_config(a: &Answers) -> String {
    let mut out = String::new();
    out.push_str("# Generated by 'pike service-install'\n\n[server]\n");
    out.push_str(&format!("bind = {}\n", toml_string(&a.bind)));
    out.push_str(&format!("port = {}\n", a.port));
    if let Some(addr) = &a.addr {
        out.push_str(&format!("addr = {}\n", toml_string(addr)));
    }
    if let Some(url) = &a.public_url {
        out.push_str(&format!("public_url = {}\n", toml_string(url)));
    }
    if let Some(token) = &a.token {
        out.push_str(&format!("token = {}\n", toml_string(token)));
    }
    out.push_str("timeout_minutes = 0\nmax_downloads = 0\n");

    out.push_str("\n[falcon]\n");
    out.push_str(&format!("client_id = {}\n", toml_string(&a.client_id)));
    out.push_str(&format!(
        "client_secret = {}\n",
        toml_string(&a.client_secret)
    ));
    out.push_str(&format!("cloud = {}\n", toml_string(&a.cloud)));
    out.push_str(&format!("cid = {}\n", toml_string(&a.cid)));

    out.push_str("\n[sensors]\n");
    out.push_str(&format!("cache_dir = {}\n", toml_string(&a.cache_dir)));
    out.push_str(&format!(
        "metadata_ttl_minutes = {}\n",
        a.metadata_ttl_minutes
    ));
    out.push_str(&format!("cache_max_bytes = {}\n", a.cache_max_bytes));
    if let Some(tags) = &a.tags {
        out.push_str(&format!("tags = {}\n", toml_string(tags)));
    }
    out.push_str("default_tag = true\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::FileConfig;

    fn answers() -> Answers {
        Answers {
            client_id: "abc".into(),
            client_secret: "s3cr3t".into(),
            cloud: "eu-1".into(),
            cid: "AABBCC-01".into(),
            port: 8080,
            bind: "0.0.0.0".into(),
            addr: Some("10.20.0.5".into()),
            public_url: None,
            token: Some("labtoken01".into()),
            tags: Some("lab/crowdstrike".into()),
            cache_dir: "/var/cache/pike".into(),
            metadata_ttl_minutes: 60,
            cache_max_bytes: 21_474_836_480,
        }
    }

    #[test]
    fn config_roundtrips_through_the_parser() {
        let toml_text = render_config(&answers());
        let parsed: FileConfig =
            toml::from_str(&toml_text).expect("generated config must parse");
        assert_eq!(parsed.server.port, Some(8080));
        assert_eq!(parsed.falcon.cloud.as_deref(), Some("eu-1"));
        assert_eq!(
            parsed.sensors.cache_dir.as_deref(),
            Some(std::path::Path::new("/var/cache/pike"))
        );
    }

    #[test]
    fn config_includes_token_and_tags() {
        let toml_text = render_config(&answers());
        assert!(toml_text.contains(r#"token = "labtoken01""#));
        assert!(toml_text.contains(r#"tags = "lab/crowdstrike""#));
    }

    #[test]
    fn optional_fields_are_omitted_when_absent() {
        let mut a = answers();
        a.public_url = None;
        a.addr = None;
        a.tags = None;
        let toml_text = render_config(&a);
        assert!(!toml_text.contains("public_url"));
        assert!(!toml_text.contains("addr ="));
        assert!(!toml_text.contains("tags ="));
        // and what was generated must still parse
        toml::from_str::<FileConfig>(&toml_text).unwrap();
    }

    #[test]
    fn secrets_are_quoted_safely() {
        let mut a = answers();
        a.client_secret = r#"has"quote\and\backslash"#.into();
        let toml_text = render_config(&a);
        let parsed: FileConfig = toml::from_str(&toml_text).unwrap();
        assert_eq!(
            parsed.falcon.client_secret.as_deref(),
            Some(r#"has"quote\and\backslash"#)
        );
    }
}
